const { ethers } = require("ethers");
const path = require("path");

// ABIs are generated by: cd blockchain && npx hardhat run scripts/deploy.js
const CiviTokenABI = require("../../blockchain/CiviToken.json");
const CiviBadgeABI = require("../../blockchain/CiviBadge.json");
const CiviAuditABI = require("../../blockchain/CiviAudit.json");

// Badge type constants — mirror of CiviBadge.sol badge index
const BADGE = {
  FIRST_REPORT: 0,
  DEDICATED_REPORTER: 1,   // 10 reports
  COMMUNITY_CHAMPION: 2,   // 50 reports
  ISSUE_CLOSER: 3,         // field worker 25 resolved
  VERIFIED_CITIZEN: 4,
  TOP_VOTER: 5,            // 100 votes
  FEEDBACK_PROVIDER: 6,    // 10 feedbacks
};

// Token reward amounts (in CIVI, expressed as integers; minted as 10^18 units)
const REWARDS = {
  REPORT_SUBMITTED: 10,
  REPORT_RESOLVED_REPORTER: 25,
  REPORT_RESOLVED_EMPLOYEE: 20,
  COMMUNITY_VOTE: 1,
  FEEDBACK_GIVEN: 5,
  REFERRAL: 15,
};

class BlockchainService {
  constructor() {
    this._initialized = false;
    this._provider = null;
    this._wallet = null;
    this._civiToken = null;
    this._civiBadge = null;
    this._civiAudit = null;
    // Serialize all write txns — prevents nonce collisions when concurrent calls race
    this._txQueue = Promise.resolve();
  }

  // Enqueue a transaction-sending task so they execute one at a time
  _enqueue(task) {
    this._txQueue = this._txQueue.then(() => task().catch(() => {}));
    return this._txQueue;
  }

  _init() {
    if (this._initialized) return;

    const rpcUrl = process.env.BLOCKCHAIN_RPC_URL;
    const privateKey = process.env.BLOCKCHAIN_PRIVATE_KEY;
    const tokenAddr = process.env.CONTRACT_CIVI_TOKEN;
    const badgeAddr = process.env.CONTRACT_CIVI_BADGE;
    const auditAddr = process.env.CONTRACT_CIVI_AUDIT;

    if (!rpcUrl || !privateKey || !tokenAddr || !badgeAddr || !auditAddr) {
      console.warn("[Blockchain] Missing env vars — blockchain features disabled.");
      return;
    }

    this._provider = new ethers.providers.JsonRpcProvider(rpcUrl);
    this._wallet = new ethers.Wallet(privateKey, this._provider);
    this._civiToken = new ethers.Contract(tokenAddr, CiviTokenABI.abi, this._wallet);
    this._civiBadge = new ethers.Contract(badgeAddr, CiviBadgeABI.abi, this._wallet);
    this._civiAudit = new ethers.Contract(auditAddr, CiviAuditABI.abi, this._wallet);
    this._initialized = true;
    console.log("[Blockchain] Service initialised. Wallet:", this._wallet.address);
  }

  get enabled() {
    this._init();
    return this._initialized;
  }

  // ─── Token Rewards ────────────────────────────────────────────────────────

  async mintTokens(walletAddress, amount, reason) {
    if (!this.enabled) return null;
    return new Promise((resolve) => {
      this._enqueue(async () => {
        try {
          const amountWei = ethers.utils.parseUnits(String(amount), 18);
          const tx = await this._civiToken.mint(walletAddress, amountWei, reason);
          await tx.wait(1);
          console.log(`[Blockchain] Minted ${amount} CIVI to ${walletAddress}: ${reason}`);
          resolve(tx.hash);
        } catch (err) {
          console.error("[Blockchain] mintTokens failed:", err.message);
          resolve(null);
        }
      });
    });
  }

  async getTokenBalance(walletAddress) {
    if (!this.enabled) return "0";
    try {
      const bal = await this._civiToken.balanceOf(walletAddress);
      return ethers.utils.formatUnits(bal, 18);
    } catch (err) {
      console.error("[Blockchain] getTokenBalance failed:", err.message);
      return "0";
    }
  }

  // ─── Badge NFTs ───────────────────────────────────────────────────────────

  async mintBadge(walletAddress, badgeType) {
    if (!this.enabled) return null;
    return new Promise((resolve) => {
      this._enqueue(async () => {
        try {
          const already = await this._civiBadge.hasBadge(walletAddress, badgeType);
          if (already) { resolve(null); return; }
          const tx = await this._civiBadge.mint(walletAddress, badgeType);
          await tx.wait(1);
          console.log(`[Blockchain] Badge ${badgeType} minted to ${walletAddress}`);
          resolve(tx.hash);
        } catch (err) {
          console.error("[Blockchain] mintBadge failed:", err.message);
          resolve(null);
        }
      });
    });
  }

  async getUserBadges(walletAddress) {
    if (!this.enabled) return Array(7).fill(false);
    try {
      const owned = await this._civiBadge.getUserBadges(walletAddress);
      return Array.from(owned);
    } catch (err) {
      console.error("[Blockchain] getUserBadges failed:", err.message);
      return Array(7).fill(false);
    }
  }

  // ─── Audit Trail ──────────────────────────────────────────────────────────

  async recordReportCreated(reportId, title, description, category, submitterWallet) {
    if (!this.enabled) return null;
    return new Promise((resolve) => {
      this._enqueue(async () => {
        try {
          const contentHash = ethers.utils.keccak256(
            ethers.utils.toUtf8Bytes(`${reportId}:${title}:${description}:${category}`)
          );
          const actor = submitterWallet && ethers.utils.isAddress(submitterWallet)
            ? submitterWallet
            : ethers.constants.AddressZero;
          const tx = await this._civiAudit.recordCreate(reportId, contentHash, actor, category);
          await tx.wait(1);
          resolve(tx.hash);
        } catch (err) {
          console.error("[Blockchain] recordReportCreated failed:", err.message);
          resolve(null);
        }
      });
    });
  }

  async recordStatusChange(reportId, status, actorWallet) {
    if (!this.enabled) return null;
    return new Promise((resolve) => {
      this._enqueue(async () => {
        try {
          const contentHash = ethers.utils.keccak256(
            ethers.utils.toUtf8Bytes(`${reportId}:${status}:${Date.now()}`)
          );
          const actor = actorWallet && ethers.utils.isAddress(actorWallet)
            ? actorWallet
            : ethers.constants.AddressZero;
          const tx = await this._civiAudit.recordStatusChange(reportId, contentHash, status, actor);
          await tx.wait(1);
          resolve(tx.hash);
        } catch (err) {
          console.error("[Blockchain] recordStatusChange failed:", err.message);
          resolve(null);
        }
      });
    });
  }

  async getReportAuditTrail(reportId) {
    if (!this.enabled) return [];
    try {
      const filter = this._civiAudit.filters.ReportEvent(reportId);
      const createFilter = this._civiAudit.filters.ReportCreated(reportId);
      const [events, createEvents] = await Promise.all([
        this._civiAudit.queryFilter(filter),
        this._civiAudit.queryFilter(createFilter),
      ]);
      const all = [...createEvents, ...events].sort((a, b) => a.blockNumber - b.blockNumber);
      return all.map((e) => ({
        txHash: e.transactionHash,
        blockNumber: e.blockNumber,
        status: e.args.status || "submitted",
        contentHash: e.args.contentHash,
        timestamp: e.args.timestamp ? new Date(e.args.timestamp.toNumber() * 1000).toISOString() : null,
      }));
    } catch (err) {
      console.error("[Blockchain] getReportAuditTrail failed:", err.message);
      return [];
    }
  }

  // ─── High-level Reward Helpers ────────────────────────────────────────────

  async rewardReportSubmitted(walletAddress, reportCount) {
    if (!walletAddress) return;
    await this.mintTokens(walletAddress, REWARDS.REPORT_SUBMITTED, "report_submitted");
    if (reportCount >= 1) await this.mintBadge(walletAddress, BADGE.FIRST_REPORT);
    if (reportCount >= 10) await this.mintBadge(walletAddress, BADGE.DEDICATED_REPORTER);
    if (reportCount >= 50) await this.mintBadge(walletAddress, BADGE.COMMUNITY_CHAMPION);
  }

  async rewardReportResolved(reporterWallet, employeeWallet, employeeResolvedCount) {
    if (reporterWallet) {
      await this.mintTokens(reporterWallet, REWARDS.REPORT_RESOLVED_REPORTER, "report_resolved_reporter");
    }
    if (employeeWallet) {
      await this.mintTokens(employeeWallet, REWARDS.REPORT_RESOLVED_EMPLOYEE, "report_resolved_employee");
      if (employeeResolvedCount >= 25) {
        await this.mintBadge(employeeWallet, BADGE.ISSUE_CLOSER);
      }
    }
  }

  async rewardVote(voterWallet) {
    if (!voterWallet) return;
    await this.mintTokens(voterWallet, REWARDS.COMMUNITY_VOTE, "community_vote");
  }

  async rewardFeedback(userWallet, feedbackCount) {
    if (!userWallet) return;
    await this.mintTokens(userWallet, REWARDS.FEEDBACK_GIVEN, "feedback_given");
    if (feedbackCount >= 10) await this.mintBadge(userWallet, BADGE.FEEDBACK_PROVIDER);
  }
}

// Export singleton — shared across all requests in the same process
module.exports = new BlockchainService();
module.exports.BADGE = BADGE;
module.exports.REWARDS = REWARDS;
